Repository KaymeKaydex/go-vshard-router, pull requests merged in 2024-09, with the labels that each got.

#41 resolve several issues
  CHANGELOG.md
  api.go
  discovery.go
  vshard.go
Labels: bug

#54 implement new test framework with real tarantools
  CHANGELOG.md
  Makefile
  tests/tnt/Makefile
  tests/tnt/README.md
  tests/tnt/cfgmaker.go
  tests/tnt/cfgmaker.lua
  tests/tnt/concurrent_topology_test.go
  tests/tnt/router.lua
  tests/tnt/storage.lua
  tests/tnt/tnt_test.go
Labels: enhancement

#43 resolve issue #39
  CHANGELOG.md
  api.go
  api_test.go
  discovery.go
  discovery_test.go
  vshard.go
  vshard_test.go
Labels: bug

#45 resolve issue #38
  CHANGELOG.md
  api.go
  discovery.go
Labels: invalid

#47 resolve issue #46
  CHANGELOG.md
  api.go
  tests/tnt/concurrent_topology_test.go
  tests/tnt/routermap_call_test.go
  tests/tnt/storage.lua
  tests/tnt/tnt_test.go
  vshard.go
Labels: enhancement, performance

#51 resolve issue #48
  CHANGELOG.md
  api.go
  api_test.go
  discovery.go
  discovery_test.go
  providers.go
  vshard.go
Labels: enhancement, performance

#56 Add tnt test for RouterCallImpl
  CHANGELOG.md
  tests/tnt/Makefile
  tests/tnt/cfgmaker.lua
  tests/tnt/concurrent_topology_test.go
  tests/tnt/router_call_test.go
  tests/tnt/routermap_call_test.go
  tests/tnt/storage.lua
Labels: tests

#57 fix several issues (partially close #42)
  CHANGELOG.md
  api.go
  discovery.go
  replicaset.go
  tests/tnt/Makefile
  tests/tnt/concurrent_topology_test.go
  tests/tnt/discovery_test.go
  tests/tnt/router_call_test.go
  tests/tnt/routermap_call_test.go
  tests/tnt/storage.lua
  tests/tnt/tnt_test.go
  tests/tnt/topology_test.go
Labels: bug, tests

#67 resolve issue #44
  CHANGELOG.md
  discovery.go
  replicaset.go
  topology.go
  vshard.go
Labels: bug

#64 resolve issue #60
  CHANGELOG.md
  discovery.go
  vshard.go
Labels: enhancement

#68 resolve issue #42
  CHANGELOG.md
  replicaset.go
  tests/tnt/replicaset_test.go
Labels: bug, enhancement, performance, tests

#72 resolve issue #70
  CHANGELOG.md
  discovery.go
  replicaset.go
Labels: enhancement, performance

#78 add benching tests & fix ClientErrors retry
  README.md
  README_ru.md
  api.go
  tests/tnt/Makefile
  tests/tnt/call_bench_test.go
  tests/tnt/router.lua
  tests/tnt/storage.lua
  tests/tnt/tnt_test.go
Labels: bug, performance
